from Joueur import *
import Club
import Journée
import Championnat


# lefoot = Club.Club("lefoot", "Didier")
# oui = Club.Club("oui", "Marcel")
# J1 = Attaquant("Bob", 95, lefoot)
# J2 = Gardien("Jean Claude", 20, lefoot)
# J3 = Milieu("Micheline", 32, lefoot)
# print(J1)
# print(J2)
# print(J3)
# print(J1.note)
# print(J3.poste)
# print(J2.nom)
# print(lefoot.nom, lefoot.entraineur)
# lefoot.remplissage([J1,J2,J3])
# lefoot.liste_joueurs()
# lefoot.note_club()
# oui.note_club()

sb = Club.Club("Stade Brestois", "Philippe")
sr = Club.Club("Stade Rennais", "Catherine")
se = Club.Club("AS Saint Etienne", "Etienne")
gu = Club.Club("Guingamp", "Joel")

A1 = Attaquant("Kévin", 72, sb)
A2 = Attaquant("Kevine", 83, sb)
A3 = Attaquant("Keveen", 64, sb)
A4 = Attaquant("Paul", 26, sr)
A5 = Attaquant("Pol", 74, sr)
A6 = Attaquant("Paulo", 98, sr)
A7 = Attaquant("Jose", 53, se)
A8 = Attaquant("Jause", 48, se)
A9 = Attaquant("Jeauze", 98, se)
A10 = Attaquant("Kylian", 39, gu)
A11 = Attaquant("Kilian", 72, gu)
A12 = Attaquant("Kilyane", 53, gu)

G1 = Gardien("Timothée", 100, sb)
G2 = Gardien("Didier", 88, sr)
G3 = Gardien("Godefroy", 65, se)
G4 = Gardien("Armand", 79, gu)

D1 = Defenseur("Philippe", 63, sb)
D2 = Defenseur("Philipe", 73, sb)
D3 = Defenseur("filipe", 35, sb)
D4 = Defenseur("Patrick", 77, sr)
D5 = Defenseur("Patrique", 89, sr)
D6 = Defenseur("Pastric", 92, sr)
D7 = Defenseur("Guy", 97, se)
D8 = Defenseur("Gui", 73, se)
D9 = Defenseur("Pierre", 85, se)
D10 = Defenseur("Patrick", 12, gu)
D11 = Defenseur("Patrique", 53, gu)
D12 = Defenseur("Pastric", 94, gu)

M1 = Milieu("Michel", 57, sb)
M2 = Milieu("Michelle", 82, sb)
M3 = Milieu("Micheleu", 75, sb)
M4 = Milieu("Mishell", 80, sb)
M5 = Milieu("Jean", 63, sr)
M6 = Milieu("Jan", 92, sr)
M7 = Milieu("Gean", 78, sr)
M8 = Milieu("Jhan", 38, sr)
M9 = Milieu("Jo", 57, se)
M10 = Milieu("Geo", 82, se)
M11 = Milieu("Jau", 75, se)
M12 = Milieu("Jaw", 80, se)
M13 = Milieu("Jacque", 63, gu)
M14 = Milieu("Jacques", 92, gu)
M15 = Milieu("Geake", 78, gu)
M16 = Milieu("Jac", 38, gu)

sb.remplissage([A1,A2,A3,G1,D1,D2,D3,M1,M2,M3,M4])
sr.remplissage([A4,A5,A6,G2,D4,D5,D6,M5,M6,M7,M8])
se.remplissage([A7,A8,A9,G3,D7,D8,D9,M9,M10,M11,M12])
gu.remplissage([A10,A11,A12,G3,D10,D11,D12,M13,M14,M15,M16])

sb.liste_joueurs()
sb.note_club()
print("-----------------------------------")
sr.liste_joueurs()
sr.note_club()
print("-----------------------------------")
se.liste_joueurs()
se.note_club()
print("-----------------------------------")
gu.liste_joueurs()
gu.note_club()
print("-----------------------------------")

ligue1 = Championnat.Championnat("ligue 1")
ligue1.remplissage([sb, sr, se, gu])

j1 = Journée.Journee(1, ligue1)
j1.deroulement()

